# permissions for end users to view canaryapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canaryapp-viewer-role
rules:
- apiGroups:
  - canary.atze.io
  resources:
  - canaryapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - canary.atze.io
  resources:
  - canaryapps/status
  verbs:
  - get
