apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-user-canaryapp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: canaryapp-editor-role
subjects:
  - kind: ServiceAccount
    name: limited-user

