apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: canary-app-demo
  source:
    repoURL: https://github.com/AtzeDeVries/canaryop
    targetRevision: HEAD
    path: examples/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}

